//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Frameset//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;测试页面&lt;/title&gt;
        ///&lt;script&gt;
        ///var JsCall = ( typeof(JsCall) === &apos;function&apos;) ? JsCall : function(){alert(&apos;这不是EWE内核&apos;)};
        ///
        ///
        ///
        ///&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body leftmargin=&quot;0&quot; topmargin=&quot;0&quot; marginwidth=&quot;0&quot; marginheight=&quot;0&quot; style=&quot;overflow:hidden;&quot;&gt;
        ///&lt;a style=&quot;background-color:red&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string String_HtmlTransparent {
            get {
                return ResourceManager.GetString("String_HtmlTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;&lt;head&gt;&lt;script type=&quot;text/javascript&quot;&gt;&lt;/script&gt;&lt;/head&gt;&lt;body style=&quot;font-size:16px;&quot;&gt;
        ///&lt;a href=&quot;http://www.taobao.com/&quot;&gt;淘宝&lt;/a&gt;&lt;br /&gt;
        ///&lt;a href=&quot;http://www.youku.com/&quot;&gt;优酷&lt;/a&gt;&lt;br /&gt;
        ///&lt;a href=&apos;http://www.youzu.com/&apos;&gt;游族&lt;/a&gt;&lt;br /&gt;
        ///&lt;a id=&quot;baidu&quot; href=&apos;http://www.baidu.com/&apos;&gt;百度&lt;/a&gt;&lt;br /&gt;
        ///&lt;a id=&apos;baidu&apos; href=&apos;http://map.baidu.com/&apos;&gt;百度地图&lt;/a&gt;&lt;br /&gt;
        ///&lt;a href=&apos;http://www.le.com/&apos;&gt;乐视&lt;/a&gt;&lt;br /&gt;
        ///&lt;a href=&apos;http://download.csdn.net/&apos;&gt;CSDN&lt;/a&gt;&lt;br /&gt;
        ///&lt;a href=&apos;http://www.yvoschaap.com/chainrxn/&apos;&gt;2D测试&lt;/a&gt;&lt;br /&gt;
        ///&lt;a href=&apos;h [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string String_Test {
            get {
                return ResourceManager.GetString("String_Test", resourceCulture);
            }
        }
    }
}
